Convert lists to numpy arrays before using choice
we have to do this since new typing in numpy seems to have some weird side effects currently

src/cr_kyoushi/simulation/states.py:359: error: Argument "a" has incompatible type "List[Transition]"; expected "Union[Sequence[Sequence[Sequence[Sequence[Sequence[Any]]]]], <union: 2 items>]